In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving ai_engineering_ecosystem_intelligence.csv to ai_engineering_ecosystem_intelligence (1).csv

In [ ]:
df=pd.read_csv("ai_engineering_ecosystem_intelligence.csv")

ParserError: Error tokenizing data. C error: Expected 37 fields in line 3848, saw 42

In [ ]:
df = pd.read_csv("ai_engineering_ecosystem_intelligence.csv", on_bad_lines='skip')

In [ ]:
df = pd.read_csv("ai_engineering_ecosystem_intelligence.csv", quoting=1, on_bad_lines='skip')

In [ ]:
df = pd.read_csv("ai_engineering_ecosystem_intelligence.csv", sep=';', on_bad_lines='skip')

In [ ]:
df.shape

(4880, 1)

In [ ]:
df.head()

                                                                                                                                                                                                                                                      full_name,owner,repo_name,description,html_url,language,stars,forks,open_issues,size_kb,license,license_family,topics,search_topic_matched,created_at,updated_at,pushed_at,archived,visibility,repo_age_days,days_since_last_push,maintenance_status,popularity_tier,ai_category,framework_stack,deep_enrichment_applied,github_health_pct,has_readme_file,has_contributing_file,has_code_of_conduct,has_issue_template,has_license_file,releases_count,latest_release_date,release_cadence_days,dependency_manifest_found,detected_dependencies
microsoft/markitdown,microsoft,markitdown,Pytho... autogen-extension                                  langchain    markdown    microsoft-office openai                                             pdf,langchain,2024-11-13T19:56:40Z,2026-08-04T0...  AutoGen,Yes,62.0,True,False,True,False,True,20...
huggingface/agents-course,huggingface,agents-co... agents                                             course       huggingface langchain        llamaindex                                         smolagents,langchain,2025-01-16T19:50:22Z,2026-...  LlamaIndex,Yes,50.0,True,False,False,False,Tru...
langchain-ai/deepagents,langchain-ai,deepagents... deepagents                                         langchain    langgraph   python           typescript,langchain,2025-07-27T23:07:53Z,2026-... LangGraph,Yes,100.0,True,True,True,False,True,1...                                                NaN
datawhalechina/llm-universe,datawhalechina,llm-... rag,langchain,2023-10-29T16:01:22Z,2026-08-04T0... openai       NaN         NaN              NaN                                                NaN                                                                                               NaN
cloudwego/eino,cloudwego,eino,The ultimate LLM/... ai-application                                     ai-framework langchain   langchain-for-go langchaingo                                        llm-application,langchain,2024-12-04T06:47:27Z,...                                                NaN

In [ ]:
df.shape

(4880, 1)

In [ ]:
df.columns

Index(['full_name,owner,repo_name,description,html_url,language,stars,forks,open_issues,size_kb,license,license_family,topics,search_topic_matched,created_at,updated_at,pushed_at,archived,visibility,repo_age_days,days_since_last_push,maintenance_status,popularity_tier,ai_category,framework_stack,deep_enrichment_applied,github_health_pct,has_readme_file,has_contributing_file,has_code_of_conduct,has_issue_template,has_license_file,releases_count,latest_release_date,release_cadence_days,dependency_manifest_found,detected_dependencies'], dtype='object')

AttributeError: 'DataFrame' object has no attribute 'row'

In [ ]:
kgf=pd.read_csv("ai_engineering_ecosystem_intelligence.csv", engine="python", on_bad_lines="skip", quoting=1)

In [ ]:
df.iloc[0]

full_name,owner,repo_name,description,html_url,language,stars,forks,open_issues,size_kb,license,license_family,topics,search_topic_matched,created_at,updated_at,pushed_at,archived,visibility,repo_age_days,days_since_last_push,maintenance_status,popularity_tier,ai_category,framework_stack,deep_enrichment_applied,github_health_pct,has_readme_file,has_contributing_file,has_code_of_conduct,has_issue_template,has_license_file,releases_count,latest_release_date,release_cadence_days,dependency_manifest_found,detected_dependencies    AutoGen,Yes,62.0,True,False,True,False,True,20...
Name: (microsoft/markitdown,microsoft,markitdown,Python tool for converting files and office documents to Markdown.,https://github.com/microsoft/markitdown,Python,171310,12462,840,4331,MIT,Permissive,autogen, autogen-extension, langchain, markdown, microsoft-office, openai, pdf,langchain,2024-11-13T19:56:40Z,2026-08-04T06:52:55Z,2026-07-29T18:18:09Z,False,public,628,5,Active,Mega (10k+),Agent/Orchestration,LangChain), dtype: object

In [ ]:
df.head()

                                                                                                                                                                                                                                                      full_name,owner,repo_name,description,html_url,language,stars,forks,open_issues,size_kb,license,license_family,topics,search_topic_matched,created_at,updated_at,pushed_at,archived,visibility,repo_age_days,days_since_last_push,maintenance_status,popularity_tier,ai_category,framework_stack,deep_enrichment_applied,github_health_pct,has_readme_file,has_contributing_file,has_code_of_conduct,has_issue_template,has_license_file,releases_count,latest_release_date,release_cadence_days,dependency_manifest_found,detected_dependencies
microsoft/markitdown,microsoft,markitdown,Pytho... autogen-extension                                  langchain    markdown    microsoft-office openai                                             pdf,langchain,2024-11-13T19:56:40Z,2026-08-04T0...  AutoGen,Yes,62.0,True,False,True,False,True,20...
huggingface/agents-course,huggingface,agents-co... agents                                             course       huggingface langchain        llamaindex                                         smolagents,langchain,2025-01-16T19:50:22Z,2026-...  LlamaIndex,Yes,50.0,True,False,False,False,Tru...
langchain-ai/deepagents,langchain-ai,deepagents... deepagents                                         langchain    langgraph   python           typescript,langchain,2025-07-27T23:07:53Z,2026-... LangGraph,Yes,100.0,True,True,True,False,True,1...                                                NaN
datawhalechina/llm-universe,datawhalechina,llm-... rag,langchain,2023-10-29T16:01:22Z,2026-08-04T0... openai       NaN         NaN              NaN                                                NaN                                                                                               NaN
cloudwego/eino,cloudwego,eino,The ultimate LLM/... ai-application                                     ai-framework langchain   langchain-for-go langchaingo                                        llm-application,langchain,2024-12-04T06:47:27Z,...                                                NaN

In [ ]:
df.columns

Index(['full_name,owner,repo_name,description,html_url,language,stars,forks,open_issues,size_kb,license,license_family,topics,search_topic_matched,created_at,updated_at,pushed_at,archived,visibility,repo_age_days,days_since_last_push,maintenance_status,popularity_tier,ai_category,framework_stack,deep_enrichment_applied,github_health_pct,has_readme_file,has_contributing_file,has_code_of_conduct,has_issue_template,has_license_file,releases_count,latest_release_date,release_cadence_days,dependency_manifest_found,detected_dependencies'], dtype='object')

In [ ]:
df.shape

(4880, 1)